/**
 * mtc-backoffice-api
 * MTC Backoffice Composite Api
 *
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 * Contact: developers@greysystems.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AgentBasic { 
    /**
     * The agent's code
     */
    code?: string;
    /**
     * The agent's id
     */
    id?: number;
    /**
     * The agent's display name
     */
    name?: string;
}
