/**
 * mtc-backoffice-api
 * MTC Backoffice Composite Api
 *
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 * Contact: developers@greysystems.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GsGeolocationCity { 
    /**
     * The city country
     */
    country?: string;
    /**
     * The city id
     */
    id?: string;
    /**
     * The city name
     */
    name?: string;
    /**
     * The city name normalized to latin alphabet (ASCII)
     */
    nameAscii?: string;
}
