/**
 * mtc-backoffice-api
 * MTC Backoffice Composite Api
 *
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 * Contact: developers@greysystems.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SearchCustomerResponse } from './searchCustomerResponse';


export interface PaginatedResultSearchCustomerResponse { 
    /**
     * Current page number
     */
    pageNumber?: number;
    /**
     * Current page size
     */
    pageSize?: number;
    /**
     * Results of the current page
     */
    results?: Array<SearchCustomerResponse>;
    /**
     * Total number of results (with no pagination)
     */
    totalResults?: number;
}
