/**
 * mtc-backoffice-api
 * MTC Backoffice Composite Api
 *
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 * Contact: developers@greysystems.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RuleParamValue } from './ruleParamValue';


export interface Rule { 
    creationDate?: Date;
    creationUser?: string;
    id?: number;
    level?: number;
    parentRule?: number;
    ruleParamValues?: Array<RuleParamValue>;
    special?: boolean;
}
