/**
 * mtc-backoffice-api
 * MTC Backoffice Composite Api
 *
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 * Contact: developers@greysystems.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TheIdentityDocument { 
    /**
     * The identity document's expiration date
     */
    expirationDate?: string;
    /**
     * The internal identity document's id
     */
    id?: number;
    /**
     * The identity document's number
     */
    number?: string;
    /**
     * The identity document's owner
     */
    owner: string;
    /**
     * The identity document's type
     */
    type: string;
}
