language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script: npm run build 
deploy: 
  skip_cleanup: true
  provider: script
  script: npm publish  dist --access public
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^develop|master$

