/**
 * mtc-backoffice-api
 * MTC Backoffice Composite Api
 *
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 * Contact: developers@greysystems.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { CountryZone } from '../model/countryZone';
import { CreatePolicy } from '../model/createPolicy';
import { CreateRule } from '../model/createRule';
import { Policy } from '../model/policy';
import { ResponseEntity } from '../model/responseEntity';
import { RestError } from '../model/restError';
import { Rule } from '../model/rule';
import { RuleParamDescriptor } from '../model/ruleParamDescriptor';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MtcPricingControllerService {

    protected basePath = 'https://vader:9003';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * addCountryZoneMembersByTypeOfRuleAndId
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param id id
     * @param iso iso
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addCountryZoneMembersByTypeOfRuleAndIdUsingPOST(localCcy: string, scheme: string, type: string, id: number, iso: string, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public addCountryZoneMembersByTypeOfRuleAndIdUsingPOST(localCcy: string, scheme: string, type: string, id: number, iso: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public addCountryZoneMembersByTypeOfRuleAndIdUsingPOST(localCcy: string, scheme: string, type: string, id: number, iso: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public addCountryZoneMembersByTypeOfRuleAndIdUsingPOST(localCcy: string, scheme: string, type: string, id: number, iso: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling addCountryZoneMembersByTypeOfRuleAndIdUsingPOST.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling addCountryZoneMembersByTypeOfRuleAndIdUsingPOST.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling addCountryZoneMembersByTypeOfRuleAndIdUsingPOST.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling addCountryZoneMembersByTypeOfRuleAndIdUsingPOST.');
        }
        if (iso === null || iso === undefined) {
            throw new Error('Required parameter iso was null or undefined when calling addCountryZoneMembersByTypeOfRuleAndIdUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<ResponseEntity>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/country-zones/${encodeURIComponent(String(id))}/members/${encodeURIComponent(String(iso))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * createPolicyByRuleId
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param ruleId ruleId
     * @param policy policy
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPolicyByRuleIdUsingPOST(localCcy: string, scheme: string, type: string, ruleId: number, policy: CreatePolicy, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public createPolicyByRuleIdUsingPOST(localCcy: string, scheme: string, type: string, ruleId: number, policy: CreatePolicy, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public createPolicyByRuleIdUsingPOST(localCcy: string, scheme: string, type: string, ruleId: number, policy: CreatePolicy, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public createPolicyByRuleIdUsingPOST(localCcy: string, scheme: string, type: string, ruleId: number, policy: CreatePolicy, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling createPolicyByRuleIdUsingPOST.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling createPolicyByRuleIdUsingPOST.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling createPolicyByRuleIdUsingPOST.');
        }
        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling createPolicyByRuleIdUsingPOST.');
        }
        if (policy === null || policy === undefined) {
            throw new Error('Required parameter policy was null or undefined when calling createPolicyByRuleIdUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/rule/${encodeURIComponent(String(ruleId))}/policy`,
            policy,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * createRuleByTypeAndScheme
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param createRule createRule
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createRuleByTypeAndSchemeUsingPOST(localCcy: string, scheme: string, type: string, createRule: CreateRule, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public createRuleByTypeAndSchemeUsingPOST(localCcy: string, scheme: string, type: string, createRule: CreateRule, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public createRuleByTypeAndSchemeUsingPOST(localCcy: string, scheme: string, type: string, createRule: CreateRule, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public createRuleByTypeAndSchemeUsingPOST(localCcy: string, scheme: string, type: string, createRule: CreateRule, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling createRuleByTypeAndSchemeUsingPOST.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling createRuleByTypeAndSchemeUsingPOST.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling createRuleByTypeAndSchemeUsingPOST.');
        }
        if (createRule === null || createRule === undefined) {
            throw new Error('Required parameter createRule was null or undefined when calling createRuleByTypeAndSchemeUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/rule`,
            createRule,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteCountryZoneMembersByTypeOfRuleAndId
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param id id
     * @param iso iso
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE(localCcy: string, scheme: string, type: string, id: number, iso: string, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE(localCcy: string, scheme: string, type: string, id: number, iso: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE(localCcy: string, scheme: string, type: string, id: number, iso: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE(localCcy: string, scheme: string, type: string, id: number, iso: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE.');
        }
        if (iso === null || iso === undefined) {
            throw new Error('Required parameter iso was null or undefined when calling deleteCountryZoneMembersByTypeOfRuleAndIdUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<ResponseEntity>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/country-zones/${encodeURIComponent(String(id))}/members/${encodeURIComponent(String(iso))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deletePolicyById
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param ruleId ruleId
     * @param policyId policyId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePolicyByIdUsingDELETE(localCcy: string, scheme: string, type: string, ruleId: number, policyId: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public deletePolicyByIdUsingDELETE(localCcy: string, scheme: string, type: string, ruleId: number, policyId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public deletePolicyByIdUsingDELETE(localCcy: string, scheme: string, type: string, ruleId: number, policyId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public deletePolicyByIdUsingDELETE(localCcy: string, scheme: string, type: string, ruleId: number, policyId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling deletePolicyByIdUsingDELETE.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling deletePolicyByIdUsingDELETE.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling deletePolicyByIdUsingDELETE.');
        }
        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling deletePolicyByIdUsingDELETE.');
        }
        if (policyId === null || policyId === undefined) {
            throw new Error('Required parameter policyId was null or undefined when calling deletePolicyByIdUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<ResponseEntity>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/rule/${encodeURIComponent(String(ruleId))}/policy/${encodeURIComponent(String(policyId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteRuleById
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteRuleByIdUsingDELETE(localCcy: string, scheme: string, type: string, id: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public deleteRuleByIdUsingDELETE(localCcy: string, scheme: string, type: string, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public deleteRuleByIdUsingDELETE(localCcy: string, scheme: string, type: string, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public deleteRuleByIdUsingDELETE(localCcy: string, scheme: string, type: string, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling deleteRuleByIdUsingDELETE.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling deleteRuleByIdUsingDELETE.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling deleteRuleByIdUsingDELETE.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteRuleByIdUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<ResponseEntity>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/rule/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCountryZoneByTypeOfRuleAndId
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCountryZoneByTypeOfRuleAndIdUsingGET(localCcy: string, scheme: string, type: string, id: number, observe?: 'body', reportProgress?: boolean): Observable<CountryZone>;
    public getCountryZoneByTypeOfRuleAndIdUsingGET(localCcy: string, scheme: string, type: string, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CountryZone>>;
    public getCountryZoneByTypeOfRuleAndIdUsingGET(localCcy: string, scheme: string, type: string, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CountryZone>>;
    public getCountryZoneByTypeOfRuleAndIdUsingGET(localCcy: string, scheme: string, type: string, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling getCountryZoneByTypeOfRuleAndIdUsingGET.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling getCountryZoneByTypeOfRuleAndIdUsingGET.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling getCountryZoneByTypeOfRuleAndIdUsingGET.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getCountryZoneByTypeOfRuleAndIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<CountryZone>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/country-zones/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCountryZoneMembersByTypeOfRuleAndId
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCountryZoneMembersByTypeOfRuleAndIdUsingGET(localCcy: string, scheme: string, type: string, id: number, observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getCountryZoneMembersByTypeOfRuleAndIdUsingGET(localCcy: string, scheme: string, type: string, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getCountryZoneMembersByTypeOfRuleAndIdUsingGET(localCcy: string, scheme: string, type: string, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getCountryZoneMembersByTypeOfRuleAndIdUsingGET(localCcy: string, scheme: string, type: string, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling getCountryZoneMembersByTypeOfRuleAndIdUsingGET.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling getCountryZoneMembersByTypeOfRuleAndIdUsingGET.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling getCountryZoneMembersByTypeOfRuleAndIdUsingGET.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getCountryZoneMembersByTypeOfRuleAndIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<string>>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/country-zones/${encodeURIComponent(String(id))}/members`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCountryZonesByTypeOfRule
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param internal internal
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCountryZonesByTypeOfRuleUsingGET(localCcy: string, scheme: string, type: string, internal: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<CountryZone>>;
    public getCountryZonesByTypeOfRuleUsingGET(localCcy: string, scheme: string, type: string, internal: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CountryZone>>>;
    public getCountryZonesByTypeOfRuleUsingGET(localCcy: string, scheme: string, type: string, internal: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CountryZone>>>;
    public getCountryZonesByTypeOfRuleUsingGET(localCcy: string, scheme: string, type: string, internal: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling getCountryZonesByTypeOfRuleUsingGET.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling getCountryZonesByTypeOfRuleUsingGET.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling getCountryZonesByTypeOfRuleUsingGET.');
        }
        if (internal === null || internal === undefined) {
            throw new Error('Required parameter internal was null or undefined when calling getCountryZonesByTypeOfRuleUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (internal !== undefined && internal !== null) {
            queryParameters = queryParameters.set('internal', <any>internal);
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<CountryZone>>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/country-zones${encodeURIComponent(String(internal))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getPoliciesByRuleId
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param ruleId ruleId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPoliciesByRuleIdUsingGET(localCcy: string, scheme: string, type: string, ruleId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Policy>>;
    public getPoliciesByRuleIdUsingGET(localCcy: string, scheme: string, type: string, ruleId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Policy>>>;
    public getPoliciesByRuleIdUsingGET(localCcy: string, scheme: string, type: string, ruleId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Policy>>>;
    public getPoliciesByRuleIdUsingGET(localCcy: string, scheme: string, type: string, ruleId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling getPoliciesByRuleIdUsingGET.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling getPoliciesByRuleIdUsingGET.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling getPoliciesByRuleIdUsingGET.');
        }
        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling getPoliciesByRuleIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Policy>>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/rule/${encodeURIComponent(String(ruleId))}/policy`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRuleScheme
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRuleSchemeUsingGET(localCcy: string, scheme: string, observe?: 'body', reportProgress?: boolean): Observable<Array<RuleParamDescriptor>>;
    public getRuleSchemeUsingGET(localCcy: string, scheme: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<RuleParamDescriptor>>>;
    public getRuleSchemeUsingGET(localCcy: string, scheme: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<RuleParamDescriptor>>>;
    public getRuleSchemeUsingGET(localCcy: string, scheme: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling getRuleSchemeUsingGET.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling getRuleSchemeUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<RuleParamDescriptor>>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/scheme`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRulesByTypeAndScheme
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRulesByTypeAndSchemeUsingGET(localCcy: string, scheme: string, type: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Rule>>;
    public getRulesByTypeAndSchemeUsingGET(localCcy: string, scheme: string, type: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Rule>>>;
    public getRulesByTypeAndSchemeUsingGET(localCcy: string, scheme: string, type: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Rule>>>;
    public getRulesByTypeAndSchemeUsingGET(localCcy: string, scheme: string, type: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling getRulesByTypeAndSchemeUsingGET.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling getRulesByTypeAndSchemeUsingGET.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling getRulesByTypeAndSchemeUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Rule>>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/rule`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updatePolicyByRuleId
     * 
     * @param localCcy localCcy
     * @param scheme scheme
     * @param type type
     * @param ruleId ruleId
     * @param policyId policyId
     * @param policy policy
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePolicyByRuleIdUsingPUT(localCcy: string, scheme: string, type: string, ruleId: number, policyId: number, policy: CreatePolicy, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public updatePolicyByRuleIdUsingPUT(localCcy: string, scheme: string, type: string, ruleId: number, policyId: number, policy: CreatePolicy, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public updatePolicyByRuleIdUsingPUT(localCcy: string, scheme: string, type: string, ruleId: number, policyId: number, policy: CreatePolicy, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public updatePolicyByRuleIdUsingPUT(localCcy: string, scheme: string, type: string, ruleId: number, policyId: number, policy: CreatePolicy, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (localCcy === null || localCcy === undefined) {
            throw new Error('Required parameter localCcy was null or undefined when calling updatePolicyByRuleIdUsingPUT.');
        }
        if (scheme === null || scheme === undefined) {
            throw new Error('Required parameter scheme was null or undefined when calling updatePolicyByRuleIdUsingPUT.');
        }
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling updatePolicyByRuleIdUsingPUT.');
        }
        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling updatePolicyByRuleIdUsingPUT.');
        }
        if (policyId === null || policyId === undefined) {
            throw new Error('Required parameter policyId was null or undefined when calling updatePolicyByRuleIdUsingPUT.');
        }
        if (policy === null || policy === undefined) {
            throw new Error('Required parameter policy was null or undefined when calling updatePolicyByRuleIdUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authorization) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<ResponseEntity>(`${this.basePath}/pricing/${encodeURIComponent(String(localCcy))}/${encodeURIComponent(String(scheme))}/${encodeURIComponent(String(type))}/rule/${encodeURIComponent(String(ruleId))}/policy/${encodeURIComponent(String(policyId))}`,
            policy,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
